// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 16.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OREchecking
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ActivateORE - Используйте "ActivateOREParams" для передачи параметров в этот метод.
        /// </summary>
        public void ActivateORE()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIRosPump31303116л1406Window1.UIItemWindow.UIItemEdit;
            WinClient uIПодбClient = this.UIRosPump31303116л1406Window1.UIItemWindow1.UIRosPump31303116л1406Client.UIПодбClient;
            WinListItem uIItemListItem = this.UIItemWindow.UIItemWindow1.UIItemList.UIItemListItem;
            WinButton uIПрименитьButton = this.UIRosPump31303116л1406Window1.UIItemWindow1.UIRosPump31303116л1406Client.UIПрименитьButton;
            #endregion

            // Щелкните надпись
            Mouse.Click(uIItemEdit, new Point(376, 40));

            // Ввести "Control + 5" в надпись
            Keyboard.SendKeys(uIItemEdit, this.ActivateOREParams.UIItemEditSendKeys, ModifierKeys.Control);

            // Щелкните "Подб" клиент
            Mouse.Click(uIПодбClient, new Point(1672, 17));

            // Щелкните элемент списка
            Mouse.Click(uIItemListItem, new Point(50, 15));

            // Щелкните "Применить" кнопка
            Mouse.Click(uIПрименитьButton, new Point(45, 11));
        }
        
        /// <summary>
        /// ChangeOREscheme - Используйте "ChangeOREschemeParams" для передачи параметров в этот метод.
        /// </summary>
        public void ChangeOREscheme()
        {
            #region Variable Declarations
            WinClient uIRosPump31303116л1406Client = this.UIRosPump31303116л1406Window.UIItemWindow1.UIRosPump31303116л1406Client;
            WinClient uIItem1ЭClient = this.UIRosPump31303116л1406Window.UIItemWindow11.UIRosPump31303116л1406Client.UIItem1ЭClient;
            WinListItem uIItemListItem4 = this.UIItemWindow.UIItemWindow1.UIItemList.UIItemListItem4;
            #endregion

            // Щелкните "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )" клиент
            Mouse.Click(uIRosPump31303116л1406Client, new Point(674, 245));

            // Тип "Control, Shift + 2" в "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )" клиент
            Keyboard.SendKeys(uIRosPump31303116л1406Client, this.ChangeOREschemeParams.UIRosPump31303116л1406ClientSendKeys, (ModifierKeys.Control | ModifierKeys.Shift));

            // Щелкните "№1: Э" клиент
            Mouse.Click(uIItem1ЭClient, new Point(350, 16));

            // Щелкните элемент списка
            Mouse.Click(uIItemListItem4, new Point(240, 9));
        }
        
        /// <summary>
        /// CountingWithErrors - Используйте "CountingWithErrorsParams" для передачи параметров в этот метод.
        /// </summary>
        public void CountingWithErrors()
        {
            #region Variable Declarations
            WinClient uIRosPump31303116л1406Client = this.UIRosPump31303116л1406Window.UIItemWindow2.UIRosPump31303116л1406Client;
            WinClient uIRosPump31303116л1406Client1 = this.UIRosPump31303116л1406Window.UIItemWindow3.UIRosPump31303116л1406Client;
            WinClient uIItem2ЭЦНПClient = this.UIRosPump31303116л1406Window.UIItemWindow1.UIRosPump31303116л1406Client.UIItem2ЭЦНПClient;
            WinListItem uIItemListItem5 = this.UIItemWindow.UIItemWindow1.UIItemList.UIItemListItem5;
            WinClient uIRosPump31303116л1406Client2 = this.UIRosPump31303116л1406Window.UIItemWindow21.UIRosPump31303116л1406Client;
            #endregion

            // Щелкните "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )" клиент
            Mouse.Click(uIRosPump31303116л1406Client, new Point(340, 388));

            // Тип "{F9}" в "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )" клиент
            Keyboard.SendKeys(uIRosPump31303116л1406Client1, this.CountingWithErrorsParams.UIRosPump31303116л1406ClientSendKeys, ModifierKeys.None);

            // Щелкните "№2: ЭЦН-П" клиент
            Mouse.Click(uIItem2ЭЦНПClient, new Point(345, 14));

            // Щелкните элемент списка
            Mouse.Click(uIItemListItem5, new Point(231, 15));

            // Тип "{F9}" в "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )" клиент
            Keyboard.SendKeys(uIRosPump31303116л1406Client2, this.CountingWithErrorsParams.UIRosPump31303116л1406ClientSendKeys1, ModifierKeys.None);
        }
        
        /// <summary>
        /// OpenRP - Используйте "OpenRPParams" для передачи параметров в этот метод.
        /// </summary>
        public void OpenRP()
        {

            // Запустить D:\emil\Rospump 3\WellDesigner.exe с аргументами /Local
            ApplicationUnderTest wellDesignerApplication = ApplicationUnderTest.Launch(this.OpenRPParams.ExePath, this.OpenRPParams.AlternateExePath, "/Local");
        }
        
        #region Properties
        public virtual ActivateOREParams ActivateOREParams
        {
            get
            {
                if ((this.mActivateOREParams == null))
                {
                    this.mActivateOREParams = new ActivateOREParams();
                }
                return this.mActivateOREParams;
            }
        }
        
        public virtual ChangeOREschemeParams ChangeOREschemeParams
        {
            get
            {
                if ((this.mChangeOREschemeParams == null))
                {
                    this.mChangeOREschemeParams = new ChangeOREschemeParams();
                }
                return this.mChangeOREschemeParams;
            }
        }
        
        public virtual CountingWithErrorsParams CountingWithErrorsParams
        {
            get
            {
                if ((this.mCountingWithErrorsParams == null))
                {
                    this.mCountingWithErrorsParams = new CountingWithErrorsParams();
                }
                return this.mCountingWithErrorsParams;
            }
        }
        
        public virtual OpenRPParams OpenRPParams
        {
            get
            {
                if ((this.mOpenRPParams == null))
                {
                    this.mOpenRPParams = new OpenRPParams();
                }
                return this.mOpenRPParams;
            }
        }
        
        public UIRosPump31303116л1406Window UIRosPump31303116л1406Window
        {
            get
            {
                if ((this.mUIRosPump31303116л1406Window == null))
                {
                    this.mUIRosPump31303116л1406Window = new UIRosPump31303116л1406Window();
                }
                return this.mUIRosPump31303116л1406Window;
            }
        }
        
        public UIItemWindow4 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow4();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIRosPumpWindow UIRosPumpWindow
        {
            get
            {
                if ((this.mUIRosPumpWindow == null))
                {
                    this.mUIRosPumpWindow = new UIRosPumpWindow();
                }
                return this.mUIRosPumpWindow;
            }
        }
        
        public UIRosPump31303116л1406Window1 UIRosPump31303116л1406Window1
        {
            get
            {
                if ((this.mUIRosPump31303116л1406Window1 == null))
                {
                    this.mUIRosPump31303116л1406Window1 = new UIRosPump31303116л1406Window1();
                }
                return this.mUIRosPump31303116л1406Window1;
            }
        }
        #endregion
        
        #region Fields
        private ActivateOREParams mActivateOREParams;
        
        private ChangeOREschemeParams mChangeOREschemeParams;
        
        private CountingWithErrorsParams mCountingWithErrorsParams;
        
        private OpenRPParams mOpenRPParams;
        
        private UIRosPump31303116л1406Window mUIRosPump31303116л1406Window;
        
        private UIItemWindow4 mUIItemWindow;
        
        private UIRosPumpWindow mUIRosPumpWindow;
        
        private UIRosPump31303116л1406Window1 mUIRosPump31303116л1406Window1;
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "ActivateORE"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class ActivateOREParams
    {
        
        #region Fields
        /// <summary>
        /// Ввести "Control + 5" в надпись
        /// </summary>
        public string UIItemEditSendKeys = "5";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "ChangeOREscheme"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class ChangeOREschemeParams
    {
        
        #region Fields
        /// <summary>
        /// Тип "Control, Shift + 2" в "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )" клиент
        /// </summary>
        public string UIRosPump31303116л1406ClientSendKeys = "2";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "CountingWithErrors"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class CountingWithErrorsParams
    {
        
        #region Fields
        /// <summary>
        /// Тип "{F9}" в "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )" клиент
        /// </summary>
        public string UIRosPump31303116л1406ClientSendKeys = "{F9}";
        
        /// <summary>
        /// Тип "{F9}" в "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )" клиент
        /// </summary>
        public string UIRosPump31303116л1406ClientSendKeys1 = "{F9}";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "OpenRP"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class OpenRPParams
    {
        
        #region Fields
        /// <summary>
        /// Запустить D:\emil\Rospump 3\WellDesigner.exe с аргументами /Local
        /// </summary>
        public string ExePath = "D:\\emil\\Rospump 3\\WellDesigner.exe";
        
        /// <summary>
        /// Запустить D:\emil\Rospump 3\WellDesigner.exe с аргументами /Local
        /// </summary>
        public string AlternateExePath = "D:\\emil\\Rospump 3\\WellDesigner.exe";
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIRosPump31303116л1406Window : WinWindow
    {
        
        public UIRosPump31303116л1406Window()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TfrmWDMain";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )");
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow11 UIItemWindow11
        {
            get
            {
                if ((this.mUIItemWindow11 == null))
                {
                    this.mUIItemWindow11 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow11;
            }
        }
        
        public UIItemWindow2 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow2(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIItemWindow3 UIItemWindow3
        {
            get
            {
                if ((this.mUIItemWindow3 == null))
                {
                    this.mUIItemWindow3 = new UIItemWindow3(this);
                }
                return this.mUIItemWindow3;
            }
        }
        
        public UIItemWindow21 UIItemWindow21
        {
            get
            {
                if ((this.mUIItemWindow21 == null))
                {
                    this.mUIItemWindow21 = new UIItemWindow21(this);
                }
                return this.mUIItemWindow21;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        
        private UIItemWindow11 mUIItemWindow11;
        
        private UIItemWindow2 mUIItemWindow2;
        
        private UIItemWindow3 mUIItemWindow3;
        
        private UIItemWindow21 mUIItemWindow21;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TdxDockControl";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )");
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public UIRosPump31303116л1406Client UIRosPump31303116л1406Client
        {
            get
            {
                if ((this.mUIRosPump31303116л1406Client == null))
                {
                    this.mUIRosPump31303116л1406Client = new UIRosPump31303116л1406Client(this);
                }
                return this.mUIRosPump31303116л1406Client;
            }
        }
        #endregion
        
        #region Fields
        private UIRosPump31303116л1406Client mUIRosPump31303116л1406Client;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIRosPump31303116л1406Client : WinClient
    {
        
        public UIRosPump31303116л1406Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )");
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public WinClient UIЭкраныClient
        {
            get
            {
                if ((this.mUIЭкраныClient == null))
                {
                    this.mUIЭкраныClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIЭкраныClient.SearchProperties[WinControl.PropertyNames.Name] = "Экраны";
                    this.mUIЭкраныClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )");
                    this.mUIЭкраныClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIЭкраныClient;
            }
        }
        
        public WinClient UIРасчётыClient
        {
            get
            {
                if ((this.mUIРасчётыClient == null))
                {
                    this.mUIРасчётыClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIРасчётыClient.SearchProperties[WinControl.PropertyNames.Name] = "Расчёты";
                    this.mUIРасчётыClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIРасчётыClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIЭкраныClient;
        
        private WinClient mUIРасчётыClient;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TdxLayoutControl";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )");
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public UIRosPump31303116л1406Client1 UIRosPump31303116л1406Client
        {
            get
            {
                if ((this.mUIRosPump31303116л1406Client == null))
                {
                    this.mUIRosPump31303116л1406Client = new UIRosPump31303116л1406Client1(this);
                }
                return this.mUIRosPump31303116л1406Client;
            }
        }
        #endregion
        
        #region Fields
        private UIRosPump31303116л1406Client1 mUIRosPump31303116л1406Client;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIRosPump31303116л1406Client1 : WinClient
    {
        
        public UIRosPump31303116л1406Client1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )");
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public WinClient UIПодбClient
        {
            get
            {
                if ((this.mUIПодбClient == null))
                {
                    this.mUIПодбClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIПодбClient.SearchProperties[WinControl.PropertyNames.Name] = "Подб";
                    this.mUIПодбClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )");
                    #endregion
                }
                return this.mUIПодбClient;
            }
        }
        
        public WinButton UIПрименитьButton
        {
            get
            {
                if ((this.mUIПрименитьButton == null))
                {
                    this.mUIПрименитьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIПрименитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Применить";
                    this.mUIПрименитьButton.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор УШГН )");
                    #endregion
                }
                return this.mUIПрименитьButton;
            }
        }
        
        public WinClient UIItem63ЭЦНШГНнижClient
        {
            get
            {
                if ((this.mUIItem63ЭЦНШГНнижClient == null))
                {
                    this.mUIItem63ЭЦНШГНнижClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIItem63ЭЦНШГНнижClient.SearchProperties[WinControl.PropertyNames.Name] = "№6.3: ЭЦН-ШГН - ниж";
                    this.mUIItem63ЭЦНШГНнижClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIItem63ЭЦНШГНнижClient;
            }
        }
        
        public WinClient UIItem10ЭЦНРКВНнижнийнClient
        {
            get
            {
                if ((this.mUIItem10ЭЦНРКВНнижнийнClient == null))
                {
                    this.mUIItem10ЭЦНРКВНнижнийнClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIItem10ЭЦНРКВНнижнийнClient.SearchProperties[WinControl.PropertyNames.Name] = "№10: ЭЦН-РКВН - нижний насо";
                    this.mUIItem10ЭЦНРКВНнижнийнClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIItem10ЭЦНРКВНнижнийнClient;
            }
        }
        
        public WinClient UIItem1ЭClient
        {
            get
            {
                if ((this.mUIItem1ЭClient == null))
                {
                    this.mUIItem1ЭClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIItem1ЭClient.SearchProperties[WinControl.PropertyNames.Name] = "№1: Э";
                    this.mUIItem1ЭClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIItem1ЭClient;
            }
        }
        
        public WinClient UIItem62ЭВНШГНнижClient
        {
            get
            {
                if ((this.mUIItem62ЭВНШГНнижClient == null))
                {
                    this.mUIItem62ЭВНШГНнижClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIItem62ЭВНШГНнижClient.SearchProperties[WinControl.PropertyNames.Name] = "№6.2: ЭВН-ШГН - ниж";
                    this.mUIItem62ЭВНШГНнижClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIItem62ЭВНШГНнижClient;
            }
        }
        
        public WinClient UIItem2ЭЦНПClient
        {
            get
            {
                if ((this.mUIItem2ЭЦНПClient == null))
                {
                    this.mUIItem2ЭЦНПClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIItem2ЭЦНПClient.SearchProperties[WinControl.PropertyNames.Name] = "№2: ЭЦН-П";
                    this.mUIItem2ЭЦНПClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIItem2ЭЦНПClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIПодбClient;
        
        private WinButton mUIПрименитьButton;
        
        private WinClient mUIItem63ЭЦНШГНнижClient;
        
        private WinClient mUIItem10ЭЦНРКВНнижнийнClient;
        
        private WinClient mUIItem1ЭClient;
        
        private WinClient mUIItem62ЭВНШГНнижClient;
        
        private WinClient mUIItem2ЭЦНПClient;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TdxLayoutControl";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public UIRosPump31303116л1406Client2 UIRosPump31303116л1406Client
        {
            get
            {
                if ((this.mUIRosPump31303116л1406Client == null))
                {
                    this.mUIRosPump31303116л1406Client = new UIRosPump31303116л1406Client2(this);
                }
                return this.mUIRosPump31303116л1406Client;
            }
        }
        #endregion
        
        #region Fields
        private UIRosPump31303116л1406Client2 mUIRosPump31303116л1406Client;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIRosPump31303116л1406Client2 : WinClient
    {
        
        public UIRosPump31303116л1406Client2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public WinClient UIItem1ЭClient
        {
            get
            {
                if ((this.mUIItem1ЭClient == null))
                {
                    this.mUIItem1ЭClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIItem1ЭClient.SearchProperties[WinControl.PropertyNames.Name] = "№1: Э";
                    this.mUIItem1ЭClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIItem1ЭClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIItem1ЭClient;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TWDcxVerticalGrid";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public WinClient UIRosPump31303116л1406Client
        {
            get
            {
                if ((this.mUIRosPump31303116л1406Client == null))
                {
                    this.mUIRosPump31303116л1406Client = new WinClient(this);
                    #region Условия поиска
                    this.mUIRosPump31303116л1406Client.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIRosPump31303116л1406Client;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIRosPump31303116л1406Client;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TWDcxVerticalGrid";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public WinClient UIRosPump31303116л1406Client
        {
            get
            {
                if ((this.mUIRosPump31303116л1406Client == null))
                {
                    this.mUIRosPump31303116л1406Client = new WinClient(this);
                    #region Условия поиска
                    this.mUIRosPump31303116л1406Client.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIRosPump31303116л1406Client;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIRosPump31303116л1406Client;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow21 : WinWindow
    {
        
        public UIItemWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TcxImage";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
            #endregion
        }
        
        #region Properties
        public WinClient UIRosPump31303116л1406Client
        {
            get
            {
                if ((this.mUIRosPump31303116л1406Client == null))
                {
                    this.mUIRosPump31303116л1406Client = new WinClient(this);
                    #region Условия поиска
                    this.mUIRosPump31303116л1406Client.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ОРЭ )");
                    #endregion
                }
                return this.mUIRosPump31303116л1406Client;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIRosPump31303116л1406Client;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow4 : WinWindow
    {
        
        public UIItemWindow4()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Рабочий стол 1";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow12 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow12(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow12 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow12 : WinWindow
    {
        
        public UIItemWindow12(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TcxImageComboBoxListBox";
            #endregion
        }
        
        #region Properties
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemList : WinList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinListItem UIItemListItem
        {
            get
            {
                if ((this.mUIItemListItem == null))
                {
                    this.mUIItemListItem = new WinListItem(this);
                    #region Условия поиска
                    this.mUIItemListItem.SearchProperties[WinListItem.PropertyNames.Instance] = "10";
                    #endregion
                }
                return this.mUIItemListItem;
            }
        }
        
        public WinListItem UIItemListItem1
        {
            get
            {
                if ((this.mUIItemListItem1 == null))
                {
                    this.mUIItemListItem1 = new WinListItem(this);
                    #region Условия поиска
                    this.mUIItemListItem1.SearchProperties[WinListItem.PropertyNames.Instance] = "13";
                    #endregion
                }
                return this.mUIItemListItem1;
            }
        }
        
        public WinListItem UIItemListItem2
        {
            get
            {
                if ((this.mUIItemListItem2 == null))
                {
                    this.mUIItemListItem2 = new WinListItem(this);
                }
                return this.mUIItemListItem2;
            }
        }
        
        public WinListItem UIItemListItem3
        {
            get
            {
                if ((this.mUIItemListItem3 == null))
                {
                    this.mUIItemListItem3 = new WinListItem(this);
                    #region Условия поиска
                    this.mUIItemListItem3.SearchProperties[WinListItem.PropertyNames.Instance] = "8";
                    #endregion
                }
                return this.mUIItemListItem3;
            }
        }
        
        public WinListItem UIItemListItem4
        {
            get
            {
                if ((this.mUIItemListItem4 == null))
                {
                    this.mUIItemListItem4 = new WinListItem(this);
                    #region Условия поиска
                    this.mUIItemListItem4.SearchProperties[WinListItem.PropertyNames.Instance] = "2";
                    #endregion
                }
                return this.mUIItemListItem4;
            }
        }
        
        public WinListItem UIItemListItem5
        {
            get
            {
                if ((this.mUIItemListItem5 == null))
                {
                    this.mUIItemListItem5 = new WinListItem(this);
                    #region Условия поиска
                    this.mUIItemListItem5.SearchProperties[WinListItem.PropertyNames.Instance] = "6";
                    #endregion
                }
                return this.mUIItemListItem5;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIItemListItem;
        
        private WinListItem mUIItemListItem1;
        
        private WinListItem mUIItemListItem2;
        
        private WinListItem mUIItemListItem3;
        
        private WinListItem mUIItemListItem4;
        
        private WinListItem mUIItemListItem5;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIRosPumpWindow : WinWindow
    {
        
        public UIRosPumpWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "RosPump";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("RosPump");
            #endregion
        }
        
        #region Properties
        public UIОКWindow UIОКWindow
        {
            get
            {
                if ((this.mUIОКWindow == null))
                {
                    this.mUIОКWindow = new UIОКWindow(this);
                }
                return this.mUIОКWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIОКWindow mUIОКWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIОКWindow : WinWindow
    {
        
        public UIОКWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("RosPump");
            #endregion
        }
        
        #region Properties
        public WinButton UIОКButton
        {
            get
            {
                if ((this.mUIОКButton == null))
                {
                    this.mUIОКButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIОКButton.SearchProperties[WinButton.PropertyNames.Name] = "ОК";
                    this.mUIОКButton.WindowTitles.Add("RosPump");
                    #endregion
                }
                return this.mUIОКButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОКButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIRosPump31303116л1406Window1 : WinWindow
    {
        
        public UIRosPump31303116л1406Window1()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ЭЦН )";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TfrmWDMain";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ЭЦН )");
            #endregion
        }
        
        #region Properties
        public UIItemWindow5 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow5(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow13 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow13(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow5 mUIItemWindow;
        
        private UIItemWindow13 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow5 : WinWindow
    {
        
        public UIItemWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TcxCustomInnerMemo";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ЭЦН )");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUIItemEdit.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ЭЦН )");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIItemWindow13 : WinWindow
    {
        
        public UIItemWindow13(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TdxLayoutControl";
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ЭЦН )");
            #endregion
        }
        
        #region Properties
        public UIRosPump31303116л1406Client3 UIRosPump31303116л1406Client
        {
            get
            {
                if ((this.mUIRosPump31303116л1406Client == null))
                {
                    this.mUIRosPump31303116л1406Client = new UIRosPump31303116л1406Client3(this);
                }
                return this.mUIRosPump31303116л1406Client;
            }
        }
        #endregion
        
        #region Fields
        private UIRosPump31303116л1406Client3 mUIRosPump31303116л1406Client;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "16.0.32802.440")]
    public class UIRosPump31303116л1406Client3 : WinClient
    {
        
        public UIRosPump31303116л1406Client3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ЭЦН )");
            #endregion
        }
        
        #region Properties
        public WinClient UIПодбClient
        {
            get
            {
                if ((this.mUIПодбClient == null))
                {
                    this.mUIПодбClient = new WinClient(this);
                    #region Условия поиска
                    this.mUIПодбClient.SearchProperties[WinControl.PropertyNames.Name] = "Подб";
                    this.mUIПодбClient.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ЭЦН )");
                    #endregion
                }
                return this.mUIПодбClient;
            }
        }
        
        public WinButton UIПрименитьButton
        {
            get
            {
                if ((this.mUIПрименитьButton == null))
                {
                    this.mUIПрименитьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIПрименитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Применить";
                    this.mUIПрименитьButton.WindowTitles.Add("RosPump 3.13.0.3116л / 14.06.2023 ( Подбор ЭЦН )");
                    #endregion
                }
                return this.mUIПрименитьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIПодбClient;
        
        private WinButton mUIПрименитьButton;
        #endregion
    }
}
